name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - cloudpickle=1.6.0
  - conda=4.9.2
  - conda-package-handling=1.7.2
  - cryptography=3.2.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.1.0
  - decorator=4.4.2
  - freetype=2.10.4
  - idna=2.10
  - imageio=2.9.0
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.3.0
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libtiff=4.1.0
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - ncurses=6.2
  - networkx=2.5
  - nomkl=3.0
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pillow=8.1.0
  - pip=20.2.4
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - readline=8.0
  - requests=2.24.0
  - ruamel_yaml=0.15.87
  - scikit-image=0.17.2
  - scipy=1.5.2
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.51.0
  - urllib3=1.25.11
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - arabic-reshaper==2.1.1
    - astunparse==1.6.3
    - attrs==20.3.0
    - dataclasses==0.6
    - dukpy==0.2.3
    - esprima==4.0.1
    - et-xmlfile==1.0.1
    - freetype-py==2.2.0
    - future==0.18.2
    - gevent==21.1.2
    - gitdb==4.0.5
    - gitpython==3.1.12
    - glfw==2.0.0
    - greenlet==1.0.0
    - imageio-ffmpeg==0.4.3
    - iniconfig==1.1.1
    - javascripthon==0.11
    - jdcal==1.4.1
    - jedi==0.18.0
    - json-tricks==3.15.5
    - macropy3==1.1.0b2
    - moviepy==1.0.3
    - msgpack==1.0.2
    - msgpack-numpy==0.4.7.1
    - numexpr==2.7.2
    - numpy==1.19.5
    - openpyxl==3.0.6
    - packaging==20.8
    - pandas==1.2.1
    - parso==0.8.1
    - pluggy==0.13.1
    - proglog==0.1.9
    - psutil==5.8.0
    - psychopy==2020.2.10
    - py==1.10.0
    - pyglet==1.5.14
    - pyobjc-core==7.1
    - pyobjc-framework-cocoa==7.1
    - pyobjc-framework-quartz==7.1
    - pyopengl==3.1.5
    - pyosf==1.0.5
    - pyserial==3.5
    - pytest==6.2.1
    - python-bidi==0.4.2
    - python-gitlab==2.5.0
    - pytz==2020.5
    - pyzmq==21.0.1
    - questplus==2019.4
    - smmap==3.0.5
    - sounddevice==0.4.1
    - soundfile==0.10.3.post1
    - tables==3.6.1
    - toml==0.10.2
    - torch==1.7.0
    - torchvision==0.8.1
    - typing-extensions==3.7.4.3
    - websocket-client==0.57.0
    - wxpython==4.1.1
    - xarray==0.16.2
    - xlrd==2.0.1
    - zope-event==4.5.0
    - zope-interface==5.2.0
