name: ensemble
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - conda=4.9.2
  - conda-package-handling=1.7.2
  - cryptography=3.2.1
  - idna=2.10
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.5
  - readline=8.0
  - requests=2.24.0
  - ruamel_yaml=0.15.87
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tqdm=4.51.0
  - urllib3=1.25.11
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - alembic==1.5.1
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - certipy==0.1.3
    - cycler==0.10.0
    - dataclasses==0.6
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - future==0.18.2
    - imageio==2.9.0
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyter-telemetry==0.1.0
    - jupyterhub==1.3.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - mako==1.1.4
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.4.3
    - networkx==2.5
    - notebook==6.2.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - packaging==20.8
    - pamela==1.0.0
    - pandas==1.2.1
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.10
    - ptyprocess==0.7.0
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - python-json-logger==2.0.1
    - pytz==2020.5
    - pywavelets==1.1.1
    - pyzmq==21.0.1
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - scikit-image==0.18.1
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - send2trash==1.5.0
    - sqlalchemy==1.3.22
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2021.1.14
    - torch==1.7.0
    - torchvision==0.8.1
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
